name = "Lean4"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Lean4"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "Lean4"
